name: torganic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.3.1 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.2.1
  intl: any
  logger: ^2.1.0
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  connection_notifier: ^2.0.1
  carousel_slider: ^4.2.1
  another_flushbar: ^1.12.30
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: any
  persistent_bottom_nav_bar_v2: any
  syncfusion_flutter_pdfviewer: ^24.2.8
  custom_refresh_indicator: ^3.1.0
  appinio_video_player: ^1.2.2
  syncfusion_flutter_charts: ^24.2.9
  webview_flutter: ^4.7.0
  buttons_tabbar: ^1.3.8
  loader_overlay: ^4.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.66.2
  gap: ^3.0.1
  package_info_plus: ^6.0.0
  flutter_dynamic_icon: ^2.1.0
  flutter_app_badger: ^1.5.0
  upgrader: ^10.1.0

  # Icons
  cupertino_icons: ^1.0.6


  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  firebase_messaging: ^14.7.20
  cloud_firestore: ^4.15.10

  # Payment Gateway
  flutter_bkash: ^0.2.0
  flutter_stripe: ^10.1.1
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  awesome_notifications: ^0.8.2








dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - .env


  # Local Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
